# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: www.kssmstatus.link
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    # 프로젝트 압축
    - name: Checkout repository
      uses: actions/checkout@v2
        
    # AWS 권한 확인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    # 압축한 프로젝트를 S3로 전송
    - name: Upload to S3
      run: |
        ls -l
        aws s3 cp --region ap-northeast-2 ./index.html s3://$S3_BUCKET_NAME/index.html

